# Generated by Django 2.2.4 on 2019-11-25 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_img', models.ImageField(blank=True, upload_to='productimage')),
                ('product_avail', models.IntegerField()),
                ('saveDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now_add=True)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Category')),
            ],
        ),
    ]
