# Generated by Django 2.2.4 on 2019-12-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uaddid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
    ]
