# Generated by Django 2.2.4 on 2019-12-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20191212_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='uaddid',
            new_name='useradd',
        ),
    ]
