# Generated by Django 2.2.4 on 2019-12-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20191212_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='useradd',
            new_name='uaddid',
        ),
    ]
