# Generated by Django 2.2.4 on 2019-12-13 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191212_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uaddid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
