# Generated by Django 2.2.4 on 2019-12-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20191213_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uaddid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
    ]
