# Generated by Django 2.2.4 on 2019-12-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20191213_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='userNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile')),
            ],
        ),
    ]
