# Generated by Django 2.2.4 on 2019-12-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='tim',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
