# Generated by Django 2.2.4 on 2019-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_usernotification_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='tim',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
