# Generated by Django 2.2.4 on 2019-12-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20191219_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyerorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerid', models.IntegerField()),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productqty', models.IntegerField()),
                ('buyermobile', models.CharField(max_length=10)),
                ('buyeraddress', models.CharField(max_length=150)),
                ('productimage', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('tim', models.DateTimeField(auto_now_add=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile')),
            ],
        ),
    ]
