# Generated by Django 2.2.4 on 2019-12-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_buyerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='productimage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
