# Generated by Django 2.2.4 on 2019-12-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20191220_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='status',
            field=models.CharField(max_length=40),
        ),
    ]
