# Generated by Django 2.2.4 on 2019-12-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20191220_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
