# Generated by Django 2.2.4 on 2019-12-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20191220_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerorder',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
