# Generated by Django 2.2 on 2020-06-02 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_auto_20191220_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uaddid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
