# Generated by Django 2.2 on 2020-06-02 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20200603_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='uaddid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.UserProfile'),
        ),
    ]
